# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  "%database_charset%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                mappings:
                    IlcfranceDataBundle:
                         type: annotation
                         dir: "%kernel.root_dir%/../src/Ilcfrance/DataBundle/OrmEntity"
                         prefix: Ilcfrance\DataBundle\OrmEntity
                         alias: IlcfranceDataBundle
                naming_strategy: doctrine.orm.naming_strategy.underscore
                metadata_cache_driver: 
                    type: service
                    id: doctrine.cache.predis
                query_cache_driver: 
                    type: service
                    id: doctrine.cache.predis
                result_cache_driver: 
                    type: service
                    id: doctrine.cache.predis
                second_level_cache:
                    enabled: true
                    log_enabled: true
                    region_cache_driver:
                        type: service
                        id: doctrine.cache.predis
                    region_lock_lifetime: 20
                    region_lifetime: 30
                    regions:
                        region_locales:
                            lifetime: 300
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_roles:
                            lifetime: 300
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_users:
                            lifetime: 300
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_users_pictures:
                            lifetime: 300
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_stagaires:
                            lifetime: 300
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        ilcfrance_stagaire_records:
                            lifetime: 300
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        ilcfrance_documents:
                            lifetime: 300
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis

