# Syfony2 framework
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
        hinclude_default_template: 'SasedevSharedBundle::hinclude.html.twig'
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
#        handler_id:  session.handler.native_file
        handler_id:  snc_redis.session.handler # session.mongo.handler # session.handler.native_file
#        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        name: "Ilcfrance"
        cookie_lifetime: 2592000 # optional, it is set to 30 days here #3600
        cookie_domain: .%domain%
        gc_probability: 0
        gc_maxlifetime: 2592000 # optional, it is set to 30 days here #7200
    fragments: { path: /_fragment }
    http_method_override: true
    assets: ~
    cache:
        app: cache.adapter.redis
        default_redis_provider: "%redis_dns%"
    serializer:
        cache: serializer.mapping.cache.apc