# JMS DI
jms_di_extra:
    locations:
        all_bundles: true
        directories: ["%kernel.root_dir%/../src/"]
    automatic_controller_injections:
        properties:
            request: "@request"
            router: "@router"
        method_calls:
            setRouter: ["@router"]

