# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

    twig.extension.i18n:
       class: Twig_Extensions_Extension_I18n
       tags:
           - { name: twig.extension }

    twig.extension.array:
       class: Twig_Extensions_Extension_Array
       tags:
           - { name: twig.extension }

    twig.extension.string_loader:
       class: Twig_Extension_StringLoader
       tags:
           - { name: twig.extension }

    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }
            
    doctrine.cache.predis:
        class: '%snc_redis.doctrine_cache_predis.class%'
        arguments: [ '@snc_redis.cache' ]

