parameters:
    mail_from: "system@predator.loc"
    mail_from_name: "ILCFrance.com"
    sitename: "PassportStagiaire.ILCFrance.com"
    mailtos:
        - { name: 'Salah Abdelkadeur Seif Eddine', email: 'sasedev@G3-710.predator.loc' }
    domain: 'passportstagiaire.ilcfrance.predator.loc'
twig:
    globals:
        default_locale: "%locale%"
        sitename: "PassportStagiaire.ILCFrance.com"
        siteauthor: "Salah Abdelkadeur Seif Eddine | SASEDev"
